spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://todoapp.cghqknuwp2cc.us-east-2.rds.amazonaws.com:3306/todoapp
    username: ParvizValiyev
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: talib114@outlook.com
    password: taliB5836
    properties:
      mail:
        smtp:
          auth:true:
          starttls:
            enable:true:

server:
  port: 5000


